### ISSUE TITLE
Continous deployment with GitHub actions

### ISSUE THREAD

**Issue by ReadyPlayerEmma** [FoldingCommunity/fah-stats-front-end#15]
I'd like to be able to make a code change and have GitHub re-build the project and publish it to the pages branch. Currently it appears that you have to build the project offline and actually commit the app itself. The actions workflow should keep the built app in another branch and any time a merge to dev happens, it should build and deploy pages to that branch.

Having this automation is also nice because tests and other checks can be automated upon PRs being submitted, and required to pass before merging.

**Comment by parvez** [comment]
Build CI is set up. All pushes to dev will be published to gh-pages branch that is mapped to the github pages.
