### ISSUE TITLE
Blank project page on API 404 response

### ISSUE THREAD

**Issue by parvez** [FoldingCommunity/fah-stats-front-end#34]
https://api.foldingathome.org/project/17802 returns 404 (many more are returning 404)
https://api.foldingathome.org/project/14188 even though in the project list api it has contact as "shahlo.solieva" but the api shows Prof. Vincent Voelz
![Screen Shot 2021-02-08 at 6 51 25 PM](https://user-images.githubusercontent.com/126749/107327187-9212a700-6a61-11eb-847c-8d43019da420.png)
![Screen Shot 2021-02-08 at 6 51 54 PM](https://user-images.githubusercontent.com/126749/107327193-94750100-6a61-11eb-82db-86edc523ab47.png)

**Comment by jcoffland** [comment]
404 is a valid and normal response.  The project page should handle this and display something meaningful like ``No description for this project yet``.

e.g: https://stats.foldingathome.org/project/13451
https://api.foldingathome.org/project/13451
