### ISSUE TITLE
Monthly Users API returning multiple users with same name and ID

### ISSUE THREAD

**Issue by parvez** [FoldingCommunity/fah-stats-front-end#35]
multiple users with the same name and id but different positions in list of 1000
API: https://api2.foldingathome.org/team/monthly?month=2&year=2021

![Screen Shot 2021-02-08 at 10 42 22 PM](https://user-images.githubusercontent.com/126749/107327325-d140f800-6a61-11eb-844a-f74a6e41d33a.png)

**Comment by ReadyPlayerEmma** [comment]
@parvez Is this resolved now that the other bug that was showing multiple anonymous users on the front page is fixed?

**Comment by shreyashah1903** [comment]
The API is updated now. And this issue seems to be fixed already.
