### ISSUE TITLE
UI Enhancements

### ISSUE THREAD

**Issue by parvez** [FoldingCommunity/fah-stats-front-end#57]
- Navigation Bar needs to be enhanced to differentiate between the main Folding@Home Site.
- Include Dark theme switcher
- Making the site Research centric
- Include protein 3d representation
- Setup Backend API for research data

**Comment by jcoffland** [comment]
These should be separate enhancement issues.

**Comment by jcoffland** [comment]
Please open separate issues.  Note, some of these don't fit well with our current development plans.  We can discuss this further in a meeting.
