### ISSUE TITLE
Donor list has multiple Anonymous

### ISSUE THREAD

**Issue by parvez** [FoldingCommunity/fah-stats-front-end#60]
I see the issue with two anonymous users in monthly api is from the backend api for march 2021 data. 
https://api2.foldingathome.org/user/monthly?month=2&year=2021 (Good Data)
https://api2.foldingathome.org/user/monthly?month=3&year=2021 (Duplicate Anonymous)

**Comment by ReadyPlayerEmma** [comment]
This should be resolved now.
