### ISSUE TITLE
New stats site breaks web client

### ISSUE THREAD

**Issue by anand-bhat** [FoldingCommunity/fah-stats-front-end#62]
There have been reports of the web client no longer displaying [team stats](https://github.com/FoldingAtHome/fah-issues/issues/1639) and [project stats](https://github.com/FoldingAtHome/fah-issues/issues/1638).

![image](https://user-images.githubusercontent.com/7332442/114403485-2d520500-9be8-11eb-8c05-5aec900907ba.png)

It appears the web client used to make XHRs to `stats.foldingathome.org/project?id=XXXXX` and `stats.foldingathome.org/user?user=X&team=Y&passkey=Z` (via a redirect from `apps.foldingathome.org/stats.py?user=X&team=Y&passkey=Z`) and these URLs in the new site no longer respond with the same content as `statsclassic` does. I've added comments in those issue reports.

Other reports of breakages from other parts of the web client: https://foldingforum.org/viewtopic.php?f=108&t=37061

I'm not sure if the fix for this is to build those endpoints in the new site or update the web client to use an equivalent but different endpoint on the new site or `api.foldingathome.org`. I'm reporting this here but feel free to move it to https://github.com/FoldingAtHome/fah-web-client/issues if this needs be addressed in the client.

**Comment by NobodyFAH** [comment]
I may or may not have the rights/power to fix that

though I'm unsure if the others would be happy with me just changing things

**Comment by NobodyFAH** [comment]
For now I'll just wait to get permissions from the others

**Comment by NobodyFAH** [comment]
Since the bug (as far as I know) seems to have been fixed this issue can be closed, can it?

**Comment by parvez** [comment]
@ReadyPlayerEmma  fixed by configuring cloudflare. Future client would use the API instead of stats domain jquery callback

**Comment by ReadyPlayerEmma** [comment]
Yes, for the time being we have proxied the requests using those deprecated APIs to the old stats site. The web client will be updated to use the new APIs at a later time as part of new client development.
