### ISSUE TITLE
Project links from FAHControl do not work

### ISSUE THREAD

**Issue by gunnarre** [FoldingCommunity/fah-stats-front-end#67]
Project links from the Adavanced GUI (FAHControl) point to URLs of this type
https://apps.foldingathome.org/project.py?p=13446
which is supposed to point to a page about the project in question. In the new stats site it just points to a list of all projects. 

Expected behavior: https://apps.foldingathome.org/project.py?p=[projectID] should link to the project in question.

**Comment by parvez** [comment]
@ReadyPlayerEmma could you add redirection in cloudfront to point
`https://stats.foldingathome.org/project?p=[projectID]`
-> to ->
`https://stats.foldingathome.org/project/[projectID]`

**Comment by parvez** [comment]
Fixed!
