### ISSUE TITLE
Font used for user name and team name has to differentiate uppercase and lowercase.

### ISSUE THREAD

**Issue by toTOWfr** [FoldingCommunity/fah-stats-front-end#71]
Because I am toTOW and not totow, user name font has to be able to display uppercase character when they are needed :
Correct display in old stats : https://statsclassic.foldingathome.org/donor/toTOW
Incorrect display in new stats : https://stats.foldingathome.org/donor/25874

The same applies to team page displays, with an example from PC Master Race - PCMR which is not pc master race - pcmr :
Correct display in old stats : https://statsclassic.foldingathome.org/team/225605
Incorrect display in new stats : https://stats.foldingathome.org/team/225605

**Comment by parvez** [comment]
Fixed...
https://statsbeta.foldingathome.org/donor/25874
https://statsbeta.foldingathome.org/team/225605
