### ISSUE TITLE
Broken links on https://foldingathome.org/statistics/

### ISSUE THREAD

**Issue by toTOWfr** [FoldingCommunity/fah-stats-front-end#72]
It's not directly an issue with the new statistic page, but as a side effect, links are broken on https://foldingathome.org/statistics/

Donor statistics link points to https://stats.foldingathome.org/donors which give a Page not found error.
Teams statistics link points to https://stats.foldingathome.org/teams which give a Page not found error.

Other links on that page are fine.

**Comment by parvez** [comment]
@ReadyPlayerEmma will do it through cloudfront

**Comment by parvez** [comment]
Fixed!
