### ISSUE TITLE
Expand donor and team view to use all screen space.

### ISSUE THREAD

**Issue by toTOWfr** [FoldingCommunity/fah-stats-front-end#73]
The views in donor and team pages should be expanded (and centred) to not waste all this space on most screens, as it is seen in this screenshot :
![image](https://user-images.githubusercontent.com/83313428/116315427-cc622980-a7b0-11eb-830e-87caa85f4825.png)

**Comment by parvez** [comment]
agree! made the width consistent for project, team and donor cards.

https://statsbeta.foldingathome.org/donor/348895
https://statsbeta.foldingathome.org/team/234980
https://statsbeta.foldingathome.org/project/13446

**Comment by toTOWfr** [comment]
It looks much better. I think you still have some room for expansion, maybe to align it with the Team Donors tab width ?

**Comment by parvez** [comment]
true. agree with you. looks better full-width
