### ISSUE TITLE
Did we loose the Points Award ?

### ISSUE THREAD

**Issue by toTOWfr** [FoldingCommunity/fah-stats-front-end#76]
In previous statistics, we used to have two awards available :
- the Total score certificate available here : https://apps.foldingathome.org/awards?user=25874 (note that the link used to be broken, and &type=score has to be removed in order to get it to work fine).
- the Total WUs certificate available here : https://apps.foldingathome.org/awards?user=25874&type=wus

In the new stats, I only see one link available in My Award, the WUs one : https://apps.foldingathome.org/awards?user=25874&type=wus ... would it be possible to get the Total score award back ? Maybe as a drop down menu with the two choices after a click on My Award field, which could be renamed to My Awards (and maybe allow to add more awards later) ?

**Comment by parvez** [comment]
yes, plan is to enhance the certificate. We were brainstorming to have both score and wus show up in the same certificate. Will that work for you?

**Comment by toTOWfr** [comment]
Yes, it's a good idea to group everything in the same certificate. 👍

**Comment by jcoffland** [comment]
For now we should just add a second link to the points certificate.  If an enhanced certificate is created at some later date it can replace these two links.
