### ISSUE TITLE
Add links to donor and team statistics on stats main page

### ISSUE THREAD

**Issue by toTOWfr** [FoldingCommunity/fah-stats-front-end#77]
On https://statsbeta.foldingathome.org/ (main page) after displaying a donor profile in My Donor Profile, it might be useful to add the following links :
- link to donor statistics page on donor name
- link to donor statistics page on ID field
- link to team statistics page on each entry of My Teams list

**Comment by parvez** [comment]
Let me think about 1 and 2.
3 is fixed!

**Comment by Delizald** [comment]
This is already completed no? Clicking on a donor's name takes you to their statics page:

![image](https://user-images.githubusercontent.com/5884968/124292319-0d611c00-db1b-11eb-8961-9c0b8d419edd.png)

**Comment by toTOWfr** [comment]
You're not looking at the right part of the page. I'm talking about the Donor Information panel on the left :
![image](https://user-images.githubusercontent.com/83313428/125659885-fa5a8173-2700-45e6-8d8a-a71f4be4d517.png)

**Comment by joe-h-fah** [comment]
The fix appears to have broken lookups by donor names, see this forum post - https://foldingforum.org/viewtopic.php?t=38062.  Entering any donor name into - https://stats.foldingathome.org - or - https://stats.foldingathome.org/donor - results in nothing happening or a "no data" message.

**Comment by shreyashah1903** [comment]
Seems to be caused by a change in the api. I will take a look at it.

**Comment by shreyashah1903** [comment]
Should be fixed now.
