### ISSUE TITLE
Add totals on OS Page

### ISSUE THREAD

**Issue by parvez** [FoldingCommunity/fah-stats-front-end#83]
https://statsbeta.foldingathome.org/os
New stats page does not show totals similar to old stats page
![Screen Shot 2021-05-27 at 5 48 35 PM](https://user-images.githubusercontent.com/126749/119913830-c6787900-bf13-11eb-8b29-68058f637748.png)

**Comment by Delizald** [comment]
I can help. Does data need to be sorted, or can it be fixed like old stats page?

**Comment by Delizald** [comment]
Working on it on: 
https://github.com/Delizald/fah-stats-front-end/tree/issue-83

**Comment by Delizald** [comment]
This is what I've got so far:

![image](https://user-images.githubusercontent.com/5884968/120049930-343ea680-bfe1-11eb-912f-c4c4bdd06618.png)

I had to use my own Table component instead of the DataTable that was originally defined because I don't know why the "Total" row wasn't being rendered.

**Comment by Delizald** [comment]
New commit:
![image](https://user-images.githubusercontent.com/5884968/120050240-54229a00-bfe2-11eb-9270-e1971b763083.png)

The table is missing the **'CPU cores'** column from the old site. Should I add it? @parvez  @ReadyPlayerEmma

**Comment by Delizald** [comment]
Added a PR for this: https://github.com/FoldingCommunity/fah-stats-front-end/pull/84

**Comment by Delizald** [comment]
PR for this issue:

https://github.com/FoldingCommunity/fah-stats-front-end/pull/85

**Comment by Delizald** [comment]
This can be closed as this was solved on commit https://github.com/FoldingCommunity/fah-stats-front-end/commit/8ffc7ee730959b1fd40ffdf73d071faf30fc31ed

**Comment by ReadyPlayerEmma** [comment]
Closed with #85
